force-app/main/default/objects/Expense_Item__c/Expense_Item__c.object-meta.xml
<CustomObject>
    <label>Expense Item</label>
    <nameField>
        <label>Expense Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expense Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense_Item__c/fields/Total_Expense__c.field-meta.xml
<CustomField>
    <fullName>Total_Expense__c</fullName>
    <label>Total Expense</label>
    <summarizedField>Expense__c.Expense_Amount__c</summarizedField>
    <summaryForeignKey>Expense__c.Expense_Item__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/ExpApp_ExpenseController.cls
public class ExpApp_ExpenseController {
    @AuraEnabled
    public static Decimal ExpApp_TotalExpenses(){
        AggregateResult expenses = [SELECT SUM(Total_Expense__c)totalExpense FROM Expense_Item__c];
        Decimal TotalExpense = (Decimal)expenses.get('totalExpense');
        return TotalExpense;
    }
    
    @AuraEnabled
    public static User getUserInfo(){
        return [select Id, Name, SmallPhotoUrl, FullPhotoUrl
                from User
                where Id = :UserInfo.getUserId()];
    }
     
}